### ISSUE TITLE
ModSecurity false positive file editor addon

### ISSUE THREAD

**Issue by thetux07** [jhampson-dbre/nginx-proxy-waf#3]
hello thank you for your work !
i have a false posisitive detection with the file editor addon : 

`2021/04/12 12:02:49 [error] 254#254: *15730 [client ****] ModSecurity: Access denied with code 403 (phase 4). Matched "Operator `Ge' with parameter `4' against variable `TX:OUTBOUND_ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/owasp-modsecurity-crs/rules/RESPONSE-959-BLOCKING-EVALUATION.conf"] [line "128"] [id "959100"] [rev ""] [msg "Outbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "0"] [ver "OWASP_CRS/3.3.1"] [maturity "0"] [accuracy "0"] [tag "anomaly-evaluation"] [hostname "****"] [uri "/api/hassio_ingress/oWD9BImRi4BTOXJ1RhmwmIK_uDnAHbXok9mT7iJMiU4/"] [unique_id "1618221768"] [ref ""] while sending to client, client: ****, server: ***, request: "GET /api/hassio_ingress/oWD9BImRi4BTOXJ1RhmwmIK_uDnAHbXok9mT7iJMiU4/ HTTP/2.0", upstream: "http://****/api/hassio_ingress/oWD9BImRi4BTOXJ1RhmwmIK_uDnAHbXok9mT7iJMiU4/", host: "****", referrer: "https://****/core_configurator/dashboard"
2021/04/12 12:02:49 [alert] 254#254: *15730 header already sent while sending to client, client: ****, server: ****, request: "GET /api/hassio_ingress/oWD9BImRi4BTOXJ1RhmwmIK_uDnAHbXok9mT7iJMiU4/ HTTP/2.0", upstream: "http://***/api/hassio_ingress/oWD9BImRi4BTOXJ1RhmwmIK_uDnAHbXok9mT7iJMiU4/", host: "****", referrer: "https://***/core_configurator/dashboard"`

thank you
ragards

**Comment by jhampson-dbre** [comment]
Thanks for reporting a false positive detection. Is there any specific action while using File Editor addon that triggers the false positive (i.e. opening a file, saving a file, etc.)?

I'm the meantime, I hope you have seen the local workarounds for bypassing modsecurity so you can successfully use File Editor addon: https://github.com/jhampson-dbre/nginx-proxy-waf/blob/main/nginx_proxy/DOCS.md#known-issues-and-limitations

**Comment by thetux07** [comment]
thank you for your reply,
yes i see it ! and i'm in DetectionOnly mode for wait
for File editor, it's when i open the addon, therefore i cant use this, it doesn't open

**Comment by jhampson-dbre** [comment]
Thanks for the info. I am able to reproduce this on my system so I should be able to create and test an exclusion rule.

Can you confirm that in DetectionOnly mode you are able to use File Editor? Nothing should be blocked by Nginx Proxy WAF in DetectionOnly mode, so if you are still having problems make sure the Nginx Proxy WAF addon has been restarted after changing the configuration to DetectionOnly.

**Comment by thetux07** [comment]
hello,
yes, in DetectionOnly, mode it work, i can open File Editor Addon but in "On" mode it don't work

**Comment by jhampson-dbre** [comment]
This should be resolved in v3.0.16 just released. Please let me know if you find otherwise. Thanks again for reporting this false positive!

**Comment by thetux07** [comment]
i just update your nginx addon and it work !! thank you
