### ISSUE TITLE
another ModSecurity false positive 

### ISSUE THREAD

**Issue by thetux07** [jhampson-dbre/nginx-proxy-waf#4]
hello,
i have another false positive alert. it with Grafana and my Monitoring Energie Dashboard
Grafana it open but i don't have any value 
it work with DetectionOnly mode.
thank you

`2021/04/15 08:58:49 [error] 254#254: *3 [client ***] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/owasp-modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "139"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.1"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "***"] [uri "/api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/api/datasources/proxy/1/query"] [unique_id "1618469929"] [ref ""], client: ***, server: ***, request: "GET /api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/api/datasources/proxy/1/query?db=homeassistant&q=SELECT%20mean(%22value%22)%20FROM%20%22kWh%22%20WHERE%20(%22domain%22%20%3D%20%27sensor%27%20AND%20%22entity_id%22%20%3D%20%27chauffage_daily_energy%27)%20AND%20time%20%3E%3D%20now()%20-%2024h%20GROUP%20BY%20time(15m)%20fill(null)&epoch=ms HTTP/2.0", host: "***", referrer: "https://***/api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/d/GGSGtJzgk/energy-monitoring?orgId=1&refresh=5s"
2021/04/15 08:58:49 [error] 254#254: *3 [client ***] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/owasp-modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "139"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.1"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "***"] [uri "/api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/api/datasources/proxy/1/query"] [unique_id "1618469929"] [ref ""], client: ***, server: ***, request: "GET /api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/api/datasources/proxy/1/query?db=homeassistant&q=SELECT%20mean(%22value%22)%20FROM%20%22kWh%22%20WHERE%20(%22entity_id%22%20%3D%20%27ballon_eau_chaude_daily_energy%27)%20AND%20time%20%3E%3D%20now()%20-%201d%20GROUP%20BY%20time(15m)%20fill(null)&epoch=ms HTTP/2.0", host: "***", referrer: "https://***/api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/d/GGSGtJzgk/energy-monitoring?orgId=1&refresh=5s"
2021/04/15 08:58:49 [error] 254#254: *3 [client ***] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/owasp-modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "139"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.1"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "***"] [uri "/api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/api/datasources/proxy/1/query"] [unique_id "1618469929"] [ref ""], client: ***, server: ***, request: "GET /api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/api/datasources/proxy/1/query?db=homeassistant&q=SELECT%20mean(%22value%22)%20FROM%20%22kWh%22%20WHERE%20(%22entity_id%22%20%3D%20%27alimentation_principale_daily_energy%27)%20AND%20time%20%3E%3D%20now()%20-%2024h%20GROUP%20BY%20time(15m)%20fill(null)&epoch=ms HTTP/2.0", host: "***", referrer: "https://***/api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/d/GGSGtJzgk/energy-monitoring?orgId=1&refresh=5s"
2021/04/15 08:58:49 [error] 254#254: *3 [client ***] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `15' ) [file "/usr/local/owasp-modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "139"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 15)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.1"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "***"] [uri "/api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/api/datasources/proxy/1/query"] [unique_id "1618469929"] [ref ""], client: ***, server: ***, request: "GET /api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/api/datasources/proxy/1/query?db=homeassistant&q=SELECT%20mean(%22value%22)%20FROM%20%22%E2%82%AC%22%20WHERE%20(%22entity_id%22%20%3D%20%27chauffage_daily_price%27)%20AND%20time%20%3E%3D%20now()%20-%2024h%20GROUP%20BY%20time(15m)%20fill(null)&epoch=ms HTTP/2.0", host: "***", referrer: "https://***/api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/d/GGSGtJzgk/energy-monitoring?orgId=1&refresh=5s"
2021/04/15 08:58:49 [error] 254#254: *3 [client ***] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `15' ) [file "/usr/local/owasp-modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "139"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 15)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.1"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "***"] [uri "/api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/api/datasources/proxy/1/query"] [unique_id "1618469929"] [ref ""], client: ***, server: ***, request: "GET /api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/api/datasources/proxy/1/query?db=homeassistant&q=SELECT%20mean(%22value%22)%20FROM%20%22%E2%82%AC%22%20WHERE%20(%22entity_id%22%20%3D%20%27ballon_eau_chaude_daily_price%27)%20AND%20time%20%3E%3D%20now()%20-%201d%20GROUP%20BY%20time(15m)%20fill(null)&epoch=ms HTTP/2.0", host: "***", referrer: "https://***/api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/d/GGSGtJzgk/energy-monitoring?orgId=1&refresh=5s"
2021/04/15 08:58:49 [error] 254#254: *3 [client ***] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `25' ) [file "/usr/local/owasp-modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "139"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 25)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.1"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "***"] [uri "/api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/api/datasources/proxy/1/query"] [unique_id "1618469929"] [ref ""], client: ***, server: ***, request: "GET /api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/api/datasources/proxy/1/query?db=homeassistant&q=SELECT%20%22value%22%20%20*0.145%2F%201%20FROM%20%22kWh%22%20WHERE%20(%22entity_id%22%20%3D%20%27tp_link_total_kwh%27)%20AND%20time%20%3E%3D%20now()%20-%2024h%3BSELECT%20mean(%22value%22)%20FROM%20%22%E2%82%AC%22%20WHERE%20(%22entity_id%22%20%3D%20%27alimentation_principale_daily_price%27)%20AND%20time%20%3E%3D%20now()%20-%2024h%20GROUP%20BY%20time(15m)%20fill(null)&epoch=ms HTTP/2.0", host: "***", referrer: "https://***/api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/d/GGSGtJzgk/energy-monitoring?orgId=1&refresh=5s"
2021/04/15 08:58:49 [error] 254#254: *3 [client ***] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/owasp-modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "139"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.1"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "***"] [uri "/api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/api/datasources/proxy/1/query"] [unique_id "1618469929"] [ref ""], client: ***, server: ***, request: "GET /api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/api/datasources/proxy/1/query?db=homeassistant&q=SELECT%20mean(%22value%22)%20FROM%20%22autogen%22.%22W%22%20WHERE%20(%22entity_id%22%20%3D%20%27alimentation_principale_puissance%27)%20AND%20time%20%3E%3D%20now()%20-%2024h%20GROUP%20BY%20time(1m)%20fill(null)&epoch=ms HTTP/2.0", host: "***", referrer: "https://***/api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/d/GGSGtJzgk/energy-monitoring?orgId=1&refresh=5s"
2021/04/15 08:58:50 [error] 254#254: *3 [client ***] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `25' ) [file "/usr/local/owasp-modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "139"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 25)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.1"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "***"] [uri "/api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/api/datasources/proxy/1/query"] [unique_id "1618469930"] [ref ""], client: ***, server: ***, request: "GET /api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/api/datasources/proxy/1/query?db=homeassistant&q=SELECT%20mean(%22value%22)%20FROM%20%22kWh%22%20WHERE%20(%22entity_id%22%20%3D%20%27alimentation_principale_yest_energy%27)%20AND%20time%20%3E%3D%20now()%20-%2030d%20GROUP%20BY%20time(1d)%20fill(null)%3BSELECT%20mean(%22value%22)%20FROM%20%22%E2%82%AC%22%20WHERE%20(%22entity_id%22%20%3D%20%27alimentation_principale_yesterday_price%27)%20AND%20time%20%3E%3D%20now()%20-%2030d%20GROUP%20BY%20time(1d)%20fill(null)&epoch=ms HTTP/2.0", host: "***", referrer: "https://***/api/hassio_ingress/Tohn09PG7gd13t3-J6pL4acxiHxt8FSju_KRrGqGsSg/d/GGSGtJzgk/energy-monitoring?orgId=1&refresh=5s"`

**Comment by thetux07** [comment]
hello, after more research, it's the influxdb who has the drop: 
`2021/04/17 20:31:54 [error] 253#253: *3 [client ***] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `10' ) [file "/usr/local/owasp-modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "139"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 10)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.1"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "***"] [uri "/api/hassio_ingress/hCtTirsDUhlwsBcpLoCODH-nvsBcJuyPQ0stfrPe7nA/chronograf/v1/sources/0/proxy"] [unique_id "1618684314"] [ref ""], client: ***, server: ha.pandipandahouse.fr, request: "POST /api/hassio_ingress/hCtTirsDUhlwsBcpLoCODH-nvsBcJuyPQ0stfrPe7nA/chronograf/v1/sources/0/proxy HTTP/2.0", host: "***", referrer: "***/api/hassio_ingress/hCtTirsDUhlwsBcpLoCODH-nvsBcJuyPQ0stfrPe7nA//worker.2503e6f3.js"
thank you`

**Comment by jhampson-dbre** [comment]
Thanks for the info. I'm sure it's trigging on the sql query in the request. I'll try to reproduce it this weekend.

**Comment by thetux07** [comment]
hello, have you find a solution?
thank you

**Comment by jhampson-dbre** [comment]
3.0.19 is released with exclusions for the detections above. The last one you posted from InfluxDB doesn't have enough detail to show what caused it to trigger. It could be related closely enough to the exclusions that were added that it will be covered by them. If not, I've added a new security.debug to provide more details about detections:
```
security:
  active: true
  mode: 'On'
  debug: true
```

Please ensure you have `security.debug` to true after updating. This way if influxdb still has an false positive, it will log all of the details. If needed, post the debug output for any remaining FPs.

**Comment by thetux07** [comment]
hello, the last version corrected the problem with influxdb !
if i have another false positive, i will activate the debug option ;-)
thank you very much
have a nice day
