### ISSUE TITLE
External exclusions file for modsecurity rules

### ISSUE THREAD

**Issue by jhampson-dbre** [jhampson-dbre/nginx-proxy-waf#6]
Users should be able to maintain their own set of rule exclusions that they can adjust to fit their specific set of add-ons, extensions, etc.

**Comment by thetux07** [comment]
hello,
for this you modify Dockerfile file : 
COPY --from=build_modsecurity /usr/local/owasp-modsecurity-crs /usr/local/owasp-modsecurity-crs
to
COPY --from=build_modsecurity /usr/local/owasp-modsecurity-crs/* /share/modesecurity/rules/

modify file nginx_proxy/rootfs/etc/nginx/modsec/main.conf
and add Include "/share/modsecurity/rules/*.conf"

**Comment by jhampson-dbre** [comment]
You can create a file using File Editor or VS Code add-on, like `/share/nginx_proxy/rules/REQUEST-900.9002-HOME-ASSISTANT-CUSTOM-EXCLUSION-RULES.conf` that you can put custom rules in. Just be aware that invalid rule syntax will cause the add-on to be unable to start with `security.customize: true`. If you try it out, let me know how it goes.
